### ISSUE TITLE
[Feature Request] Setting and command for toggling drag symbol

### ISSUE THREAD

**Issue by cptvincer** [cycsd/obsidian-card-note#21]
Awesome plugin! But 99% of the time im not draggin notes into canvases- i still use it a lot to search and filter notes, then all the dragging awesomeness when the time calls for it...

..yet the drag symbol is constantly on, also pushing all notes content to the right while doing so- wich is specially more obvious on canvas, as clicking to enter edit mode makes a sudden shift as it shoves the text some margin to the right.

My suggestions:

**Command**
A command for toggling the feature on and off- that way we can set our own hotkey to it.

**Button**
Could be on ribbon or in the cardnotes pane itself- that toggles the drag symbol on and off

**Setting**
Also a toggle. If someone wants to permantly leave it disabled they could just toggle it in settings and done.
No need for the settings being different then the two above- all the same toggle, on off. Using the hotkey or button to toggle on or off would also change the toggle on the settings.

**Comment by cycsd** [comment]
Hello, I released a new [version](https://github.com/cycsd/obsidian-card-note/releases/tag/1.3.0)  to add this feature.

Thank you for your suggestion.

**Comment by cptvincer** [comment]
Great! Just one thing missing- when the drag symbol is hidden editing cards on the canvas still pushes the editor text to the right- the symbol is now invisible but the margin it creates still happens- wich is the thing that makes the jarring text shift when editing cards.
Would it be possible to also turn that off when the command is used? If its simple i mean

**Comment by cycsd** [comment]
Fix this problem in version [1.3.1](https://github.com/cycsd/obsidian-card-note/releases/tag/1.3.1).

Thanks for the feedback.
